"""Template-preparation Agent schemas."""

from docfit.tools.template_schemas.workspace import (
    TEMPLATE_GET_CURRENT_WORK_ITEM_SCHEMA,
    TEMPLATE_GET_REVIEW_BATCH_SCHEMA,
    TEMPLATE_REPORT_AMBIGUITY_SCHEMA,
    TEMPLATE_REQUEST_CURRENT_CONTEXT_SCHEMA,
    TEMPLATE_SUBMIT_CURRENT_DECISION_SCHEMA,
)

__all__ = [
    "TEMPLATE_GET_CURRENT_WORK_ITEM_SCHEMA",
    "TEMPLATE_GET_REVIEW_BATCH_SCHEMA",
    "TEMPLATE_REPORT_AMBIGUITY_SCHEMA",
    "TEMPLATE_REQUEST_CURRENT_CONTEXT_SCHEMA",
    "TEMPLATE_SUBMIT_CURRENT_DECISION_SCHEMA",
]
