"""Template workspace Tool schemas."""

from docfit.tools.template_schemas.workspace import (
    DOCUMENT_REF_SCHEMA,
    TEMPLATE_EDIT_SCHEMA,
    TEMPLATE_FOCUS_SCHEMA,
    TEMPLATE_NEXT_SCHEMA,
    TEMPLATE_OPEN_SCHEMA,
    TEMPLATE_PUBLISH_SCHEMA,
    TEMPLATE_REGISTRY_SCHEMA,
    TEMPLATE_SEARCH_SCHEMA,
)

__all__ = [
    "DOCUMENT_REF_SCHEMA",
    "TEMPLATE_FOCUS_SCHEMA",
    "TEMPLATE_EDIT_SCHEMA",
    "TEMPLATE_NEXT_SCHEMA",
    "TEMPLATE_OPEN_SCHEMA",
    "TEMPLATE_PUBLISH_SCHEMA",
    "TEMPLATE_REGISTRY_SCHEMA",
    "TEMPLATE_SEARCH_SCHEMA",
]
