"""Content-addressed render and derived-view evidence storage."""

from __future__ import annotations

import json
import os
import re
import shutil
import tempfile
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path
from typing import Any, NoReturn

from docfit.tools.runtime import (
    JsonObject,
    ToolFailure,
    atomic_write_json,
    sha256_file,
    sha256_json,
)

_RENDER_REF = re.compile(r"^render:v2:([0-9a-f]{64})$")
_VISUAL_REF = re.compile(r"^visual:v2:([0-9a-f]{64})$")


def render_reference(identity: JsonObject) -> str:
    return f"render:v2:{sha256_json(identity)}"


def visual_reference(identity: JsonObject) -> str:
    return f"visual:v2:{sha256_json(identity)}"


@dataclass(frozen=True, slots=True)
class StoredView:
    reference: str
    path: Path
    metadata: JsonObject


class EvidenceStore:
    """One task-local store shared by normal and template Agent workflows."""

    def __init__(self, task_root: Path) -> None:
        self.task_root = task_root.resolve(strict=True)
        self.root = self.task_root / ".docfit" / "evidence"
        self.renders = self.root / "renders"

    def render_path(self, reference: Any) -> Path:
        if not isinstance(reference, str):
            self._missing("render")
        match = _RENDER_REF.fullmatch(reference)
        if match is None:
            self._missing("render")
        assert match is not None
        path = self.renders / match.group(1)
        if not path.is_dir():
            self._missing("render")
        return path.resolve(strict=True)

    def resolve_render(self, reference: Any) -> tuple[Path, JsonObject]:
        path = self.render_path(reference)
        manifest = self._read_json(path / "manifest.json")
        if manifest.get("schema_version") != 2 or manifest.get("render_ref") != reference:
            self._corrupt("render manifest")
        files = manifest.get("files")
        if not isinstance(files, list) or not files:
            self._corrupt("render file inventory")
        for item in files:
            if not isinstance(item, dict) or not isinstance(item.get("path"), str):
                self._corrupt("render file inventory")
            candidate = (path / item["path"]).resolve(strict=True)
            if path not in candidate.parents:
                self._corrupt("render file path")
            if item.get("sha256") != sha256_file(candidate):
                self._corrupt("render file hash")
        return path, manifest

    def temporary_render(self, reference: str) -> Path:
        match = _RENDER_REF.fullmatch(reference)
        if match is None:
            raise AssertionError("render reference must be generated by render_reference")
        self.renders.mkdir(parents=True, exist_ok=True)
        return Path(tempfile.mkdtemp(prefix=f".{match.group(1)}.", dir=self.renders))

    def publish_render(self, temporary: Path, reference: str) -> Path:
        match = _RENDER_REF.fullmatch(reference)
        if match is None:
            raise AssertionError("render reference must be generated by render_reference")
        target = self.renders / match.group(1)
        try:
            os.rename(temporary, target)
        except FileExistsError:
            self.resolve_render(reference)
        return target.resolve(strict=True)

    def get_or_create_view(
        self,
        *,
        render_ref: str,
        identity: JsonObject,
        stem: str,
        build: Callable[[Path], JsonObject],
    ) -> StoredView:
        render_path, _ = self.resolve_render(render_ref)
        reference = visual_reference(identity)
        opaque = reference.rsplit(":", 1)[-1]
        views = render_path / "views"
        views.mkdir(exist_ok=True)
        image = views / f"{stem}-{opaque}.png"
        sidecar = views / f"{stem}-{opaque}.json"
        if image.is_file() and sidecar.is_file():
            metadata = self._read_json(sidecar)
            if (
                metadata.get("evidence_ref") != reference
                or metadata.get("identity") != identity
                or metadata.get("image_sha256") != sha256_file(image)
            ):
                self._corrupt("visual evidence")
            return StoredView(reference, image, metadata)
        descriptor, temporary_name = tempfile.mkstemp(
            prefix=f".{stem}-{opaque}.", suffix=".png", dir=views
        )
        os.close(descriptor)
        temporary = Path(temporary_name)
        try:
            details = build(temporary)
            if not temporary.is_file() or temporary.stat().st_size == 0:
                self._corrupt("derived image")
            metadata = {
                "schema_version": 2,
                "evidence_ref": reference,
                "render_ref": render_ref,
                "identity": identity,
                "image_sha256": sha256_file(temporary),
                **details,
            }
            os.replace(temporary, image)
            atomic_write_json(sidecar, metadata)
            return StoredView(reference, image, metadata)
        finally:
            temporary.unlink(missing_ok=True)

    def resolve_view(self, reference: Any) -> StoredView:
        if not isinstance(reference, str):
            self._missing("visual")
        match = _VISUAL_REF.fullmatch(reference)
        if match is None:
            self._missing("visual")
        assert match is not None
        opaque = match.group(1)
        for sidecar in self.renders.glob(f"*/views/*-{opaque}.json"):
            metadata = self._read_json(sidecar)
            image = sidecar.with_suffix(".png")
            if (
                metadata.get("evidence_ref") == reference
                and image.is_file()
                and metadata.get("image_sha256") == sha256_file(image)
            ):
                return StoredView(reference, image, metadata)
        self._missing("visual")

    @staticmethod
    def file_inventory(root: Path, paths: list[Path]) -> list[JsonObject]:
        return [
            {
                "path": path.relative_to(root).as_posix(),
                "sha256": sha256_file(path),
                "bytes": path.stat().st_size,
            }
            for path in sorted(paths)
        ]

    @staticmethod
    def discard_temporary(path: Path) -> None:
        shutil.rmtree(path, ignore_errors=True)

    @staticmethod
    def _read_json(path: Path) -> JsonObject:
        try:
            value: Any = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as error:
            raise ToolFailure(
                status="error",
                origin="evidence",
                code="evidence_unreadable",
                message="Visual evidence cannot be read or verified.",
            ) from error
        if not isinstance(value, dict):
            EvidenceStore._corrupt("JSON evidence")
        return value

    @staticmethod
    def _missing(kind: str) -> NoReturn:
        raise ToolFailure(
            status="needs_input",
            origin="request",
            code=f"{kind}_ref_not_found",
            message=f"The {kind} evidence reference is invalid or unavailable.",
        )

    @staticmethod
    def _corrupt(label: str) -> NoReturn:
        raise ToolFailure(
            status="error",
            origin="evidence",
            code="evidence_hash_mismatch",
            message=f"The {label} failed its integrity check.",
        )
